### PR TITLE
Download page updates

### PR DESCRIPTION
**Pull request by fpapon**
- Move old series to archives page
- Add anchor for project schedule

### CODE REVIEW

**Review by jbonofre — CHANGES_REQUESTED** [review]
On the `download` page, I would add direct access (with `id`) to the release versions. Thoughts ?
The purpose is to have direct link to a specific version when announcing a release.

**Comment by fpapon** [comment]
The latest releases are in the block at the to of the `download` page and there is only for **KarafContainer** maintenance release that we have series download.

We can add an anchor to the **KarafContainer** series block.

Thoughts ?

**Comment by jbonofre** [comment]
Yeah, basically, I think it would be great to have URLs like:

* http://karaf.apache.org/download.html#container421 
* http://karaf.apache.org/download.html#cellar411
* http://karaf.apache.org/download.html#cave411
* http://karaf.apache.org/download.html#decanter210
* http://karaf.apache.org/download.html#container416

Basically any release appearing on the download page. The idea is to use such URL when announcing the release (by e-mail and tweeter).

Thoughts ?

**Comment by fpapon** [comment]
I added an anchor for the container release, for the others, the anchor work because they are at the top of the page.

**Review by jbonofre — APPROVED** [review]
LGTM, Thanks !

**Pull request merged**
